"AUTOSTART": true
"INITIALS": "YS"
"INTERACTIVE": true
"LOCATION": "anywhere"
"MOTIONPATH": "C:/Users/yd897/Documents/GitHub/diel-light-pi/activity-monitoring/motion-configs/motion.conf"
"ORGANISM": "some animal"
"OUTPATH": "output_folder_name"
"PROJECT": "project name"
"TRIALNAME": "name"
"TRIALNUM": "0"
"USER": "First Last"
