AUTOSTART: true
INITIALS: YS
INTERACTIVE: true
LOCATION: anywhere
MOTIONPATH: C:/Users/yd897/Documents/GitHub/diel-light-pi/activity-monitoring/motion-configs/motion_best.conf
ORGANISM: some_animal
OUTPATH: date_test
PROJECT: test
TRIALNAME: ''
TRIALNUM: '0'
USER: Yash_Sondhi
