source "https://rubygems.org"

gem "jekyll", "~> 4.4"
gem "just-the-docs"
gem "logger"
gem "base64"
gem "csv"

gem "jekyll-github-metadata"

group :jekyll_plugins do
  gem "jekyll-include-cache"
  gem "jekyll-sitemap"
  gem "jekyll-feed"
  gem "jekyll-seo-tag"
end

gem 'wdm', '>= 0.1.0' if Gem.win_platform?