title: Raspberry Pi's as Portable Locomotion Activity Sensors
description: A comprehensive guide to using Raspberry Pi's as a portable locomotion activity sensor. 

theme: just-the-docs

url: https://yashsondhi.github.io/diel-light-pi

aux_links:
  Template Repository: https://github.com/yashsondhi/diel-light-pi